"""
Migrator Generator - Generates a standalone Python migrator package
that end-users can install and use to migrate their code.
"""

import json
from pathlib import Path
from typing import List
from datetime import datetime

from .changelog_parser import VersionChangelog


SETUP_PY_TEMPLATE = """\
from setuptools import setup, find_packages

setup(
    name="{package_name}",
    version="{package_version}",
    description="Auto-generated code migrator for {library_name}",
    packages=find_packages(),
    install_requires=["libcst>=1.0.0"],
    entry_points={{
        "console_scripts": [
            "{package_name}={package_name}.__main__:main",
        ],
    }},
    python_requires=">=3.8",
)
"""

README_TEMPLATE = """\
# {package_name}

Auto-generated code migrator for **{library_name}**.

## Installation

```bash
pip install -e .
```

## Usage

```bash
# List available versions
python -m {package_name} list-versions

# Migrate a project
python -m {package_name} migrate --from 1.0.0 --to 2.0.0 ./my_project/

# Migrate to latest
python -m {package_name} migrate --from 1.0.0 --to latest ./my_project/

# Dry run (preview only)
python -m {package_name} migrate --from 1.0.0 --to latest ./my_project/ --dry-run

# Show diff preview
python -m {package_name} migrate --from 1.0.0 --to latest myfile.py --preview

# Downgrade
python -m {package_name} migrate --from 3.0.0 --to 1.0.0 ./my_project/
```

## Covered versions

{version_list}

---
*Generated by MigratorGen on {generated_date}*
"""


def _build_main_module(package_name: str, library_name: str,
                       migration_data: dict, version_range: str,
                       generated_date: str) -> str:
    """Build the __main__.py source code as a string (no .format() on code)."""

    # Serialize migration data once
    mdata_json_str = json.dumps(json.dumps(migration_data))

    # We build the file line by line to avoid any .format() conflicts
    # with the embedded Python code that uses f-strings and dict accesses.
    L = []

    def w(*args):
        L.append(" ".join(str(a) for a in args))

    def nl():
        L.append("")

    w('"""')
    w(package_name, "- Auto-generated code migrator for", library_name)
    w("Generated on:", generated_date)
    w("Versions covered:", version_range)
    nl()
    w("Usage:")
    w("    python -m", package_name, "list-versions")
    w("    python -m", package_name, "migrate --from 1.0.0 --to 2.0.0 ./project/")
    w("    python -m", package_name, "migrate --from 1.0.0 --to latest ./project/ --dry-run")
    w('"""')
    nl()
    w("import sys, json, argparse, difflib, re")
    w("from pathlib import Path")
    w("from typing import List, Tuple, Optional")
    nl()
    w("# Embedded migration rules (JSON string - avoids null/true/false Python syntax issues)")
    w("_MIGRATION_JSON =", mdata_json_str)
    w("MIGRATION_DATA = json.loads(_MIGRATION_JSON)")
    nl()
    w("try:")
    w("    import libcst as cst")
    w("    _CST = True")
    w("except ImportError:")
    w("    _CST = False")
    w("    print('[WARNING] libcst not found. Run: pip install libcst')")
    nl()
    nl()
    # version_key helper
    w("def _vk(v):")
    w("    return tuple(int(x) for x in re.findall(r'\\d+', v))")
    nl()
    nl()
    # dotted name helpers
    w("def _dn(node):")
    w("    if node is None: return ''")
    w("    if isinstance(node, cst.Name): return node.value")
    w("    if isinstance(node, cst.Attribute): return _dn(node.value) + '.' + node.attr.value")
    w("    return ''")
    nl()
    nl()
    w("def _mn(name):")
    w("    parts = name.split('.')")
    w("    node = cst.Name(parts[0])")
    w("    for p in parts[1:]:")
    w("        node = cst.Attribute(value=node, attr=cst.Name(p))")
    w("    return node")
    nl()
    nl()
    w("def _cn(f):")
    w("    if isinstance(f, cst.Name): return f.value")
    w("    if isinstance(f, cst.Attribute): return f.attr.value")
    w("    return ''")
    nl()
    nl()
    # Base transformer
    w("class B(cst.CSTTransformer):")
    w("    def __init__(self, r): self.r = r; self.ch = []")
    w("    def rec(self, m): self.ch.append(m)")
    nl()
    nl()
    # Rename function/class
    w("class RF(B):")
    w("    def leave_Name(self, o, u):")
    w("        if u.value == self.r.get('old_name'):")
    w("            self.rec('Renamed ' + self.r['old_name'] + ' -> ' + self.r['new_name'])")
    w("            return u.with_changes(value=self.r['new_name'])")
    w("        return u")
    nl()
    w("RC = RF  # rename_class uses same logic")
    nl()
    nl()
    # Rename attribute
    w("class RA(B):")
    w("    def leave_Attribute(self, o, u):")
    w("        if isinstance(u.attr, cst.Name) and u.attr.value == self.r.get('old_name'):")
    w("            self.rec('Renamed .' + self.r['old_name'] + ' -> .' + self.r['new_name'])")
    w("            return u.with_changes(attr=cst.Name(self.r['new_name']))")
    w("        return u")
    nl()
    nl()
    # Rename import
    w("class RI(B):")
    w("    def leave_ImportFrom(self, o, u):")
    w("        mod = _dn(u.module) if u.module else ''")
    w("        om, nm = self.r.get('old_module',''), self.r.get('new_module','')")
    w("        on, nn = self.r.get('old_name',''), self.r.get('new_name','')")
    w("        if mod != om: return u")
    w("        nmn = _mn(nm) if nm else u.module")
    w("        if isinstance(u.names, cst.ImportStar): return u.with_changes(module=nmn)")
    w("        nl2, changed = [], False")
    w("        for a in u.names:")
    w("            if _dn(a.name) == on and nn:")
    w("                nl2.append(a.with_changes(name=cst.Name(nn)))")
    w("                changed = True")
    w("                self.rec('Renamed import ' + on + ' -> ' + nn + ' in ' + nm)")
    w("            else: nl2.append(a)")
    w("        if not changed: return u")
    w("        return u.with_changes(module=nmn, names=nl2)")
    nl()
    nl()
    # Add argument
    w("class AA(B):")
    w("    def leave_Call(self, o, u):")
    w("        if _cn(u.func) != self.r.get('function_name'): return u")
    w("        for a in u.args:")
    w("            if a.keyword and a.keyword.value == self.r.get('argument_name'): return u")
    w("        dv = self.r.get('default_value') or 'None'")
    w("        na = cst.Arg(keyword=cst.Name(self.r['argument_name']),")
    w("            value=cst.parse_expression(dv),")
    w("            equal=cst.AssignEqual(whitespace_before=cst.SimpleWhitespace(''),")
    w("                whitespace_after=cst.SimpleWhitespace('')))")
    w("        args = list(u.args)")
    w("        if args: args[-1] = args[-1].with_changes(comma=cst.MaybeSentinel.DEFAULT)")
    w("        args.append(na)")
    w("        self.rec('Added ' + self.r['argument_name'] + '=' + dv + ' to ' + self.r['function_name'] + '()')")
    w("        return u.with_changes(args=args)")
    nl()
    nl()
    # Remove argument
    w("class RemA(B):")
    w("    def leave_Call(self, o, u):")
    w("        if _cn(u.func) != self.r.get('function_name'): return u")
    w("        na = [a for a in u.args if not (a.keyword and a.keyword.value == self.r.get('argument_name'))]")
    w("        if len(na) < len(u.args):")
    w("            if na: na[-1] = na[-1].with_changes(comma=cst.MaybeSentinel.DEFAULT)")
    w("            self.rec('Removed ' + self.r['argument_name'] + ' from ' + self.r['function_name'] + '()')")
    w("            return u.with_changes(args=na)")
    w("        return u")
    nl()
    nl()
    # Move module
    w("class MM(B):")
    w("    def leave_ImportFrom(self, o, u):")
    w("        mod = _dn(u.module) if u.module else ''")
    w("        if mod != self.r.get('source_module'): return u")
    w("        if isinstance(u.names, cst.ImportStar): return u")
    w("        for a in u.names:")
    w("            if _dn(a.name) == self.r.get('old_name'):")
    w("                self.rec('Moved ' + self.r['old_name'] + ' to ' + self.r['target_module'])")
    w("                return u.with_changes(module=_mn(self.r['target_module']))")
    w("        return u")
    nl()
    nl()
    # Replace with property
    w("class RWP(B):")
    w("    def leave_Call(self, o, u):")
    w("        if not isinstance(u.func, cst.Attribute): return u")
    w("        if u.func.attr.value != self.r.get('old_name'): return u")
    w("        if u.args: return u")
    w("        self.rec('Replaced ' + self.r['old_name'] + '() with .' + self.r['new_name'])")
    w("        return u.func.with_changes(attr=cst.Name(self.r['new_name']))")
    nl()
    nl()
    # Add decorator
    w("class AD(B):")
    w("    def leave_FunctionDef(self, o, u):")
    w("        if u.name.value != self.r.get('function_name'): return u")
    w("        dn = self.r.get('decorator_name')")
    w("        for d in u.decorators:")
    w("            if isinstance(d.decorator, cst.Name) and d.decorator.value == dn: return u")
    w("        nd = cst.Decorator(decorator=cst.Name(dn), leading_lines=[])")
    w("        self.rec('Added @' + dn + ' to ' + self.r['function_name'])")
    w("        return u.with_changes(decorators=[*u.decorators, nd])")
    nl()
    nl()
    # Remove decorator
    w("class RD(B):")
    w("    def leave_FunctionDef(self, o, u):")
    w("        if u.name.value != self.r.get('function_name'): return u")
    w("        dn = self.r.get('decorator_name')")
    w("        nd = [d for d in u.decorators if not (isinstance(d.decorator, cst.Name) and d.decorator.value == dn)]")
    w("        if len(nd) < len(u.decorators):")
    w("            self.rec('Removed @' + dn + ' from ' + self.r['function_name'])")
    w("            return u.with_changes(decorators=nd)")
    w("        return u")
    nl()
    nl()
    # Deprecate
    w("class Dep(B):")
    w("    def leave_SimpleStatementLine(self, o, u):")
    w("        for s in u.body:")
    w("            if isinstance(s, cst.Expr) and isinstance(s.value, cst.Call):")
    w("                fn = _cn(s.value.func)")
    w("                if fn == self.r.get('old_name'):")
    w("                    repl = self.r.get('replacement','N/A')")
    w("                    c = cst.EmptyLine(comment=cst.Comment('# DEPRECATED: ' + fn + '() use ' + repl))")
    w("                    self.rec('Marked ' + fn + '() as deprecated')")
    w("                    return u.with_changes(leading_lines=[*u.leading_lines, c])")
    w("        return u")
    nl()
    nl()
    # Change arg default
    w("class CAD(B):")
    w("    def leave_Param(self, o, u):")
    w("        if u.name.value != self.r.get('argument_name'): return u")
    w("        nd = self.r.get('default_value')")
    w("        if nd is None: return u")
    w("        self.rec('Changed default of ' + self.r['argument_name'] + ' to ' + nd)")
    w("        return u.with_changes(default=cst.parse_expression(nd))")
    nl()
    nl()
    # Transformer map
    w("_TM = {")
    w("    'rename_function': RF, 'rename_class': RC,")
    w("    'rename_attribute': RA, 'rename_import': RI,")
    w("    'add_argument': AA, 'remove_argument': RemA,")
    w("    'move_to_module': MM, 'replace_with_property': RWP,")
    w("    'add_decorator': AD, 'remove_decorator': RD,")
    w("    'deprecate_function': Dep, 'remove_function': Dep,")
    w("    'change_argument_default': CAD,")
    w("}")
    nl()
    nl()
    # Apply rule
    w("def _apply(code, rule):")
    w("    if not _CST: return code, []")
    w("    cls = _TM.get(rule.get('change_type'))")
    w("    if cls is None: return code, []")
    w("    t = cls(rule)")
    w("    try:")
    w("        return cst.parse_module(code).visit(t).code, t.ch")
    w("    except Exception as e:")
    w("        return code, ['[ERR] ' + str(e)]")
    nl()
    nl()
    # Resolve rules
    w("def _versions():")
    w("    return sorted(MIGRATION_DATA.keys(), key=_vk)")
    nl()
    nl()
    w("def _resolve(src, tgt):")
    w("    vs = _versions()")
    w("    if tgt == 'latest': tgt = vs[-1]")
    w("    sk, tk = _vk(src), _vk(tgt)")
    w("    up = tk > sk")
    w("    rules = []")
    w("    if up:")
    w("        for v in vs:")
    w("            if _vk(v) > sk and _vk(v) <= tk: rules.extend(MIGRATION_DATA[v])")
    w("    else:")
    w("        for v in reversed(vs):")
    w("            if _vk(v) > tk and _vk(v) <= sk: rules.extend(MIGRATION_DATA[v])")
    w("    return rules, tgt, up")
    nl()
    nl()
    # Public API
    w("def migrate_code(source_code, rules):")
    w("    '''Migrate source code string. Returns (new_code, changes).'''")
    w("    code, all_ch = source_code, []")
    w("    for r in rules:")
    w("        nc, ch = _apply(code, r)")
    w("        if nc != code: code = nc; all_ch.extend(ch)")
    w("    return code, all_ch")
    nl()
    nl()
    w("def migrate_file(path, rules, dry_run=False, backup=True):")
    w("    '''Migrate a file in place. Returns (was_modified, changes).'''")
    w("    path = Path(path)")
    w("    src = path.read_text(encoding='utf-8')")
    w("    nc, ch = migrate_code(src, rules)")
    w("    mod = nc != src")
    w("    if mod and not dry_run:")
    w("        if backup: path.with_suffix('.py.bak').write_text(src, encoding='utf-8')")
    w("        path.write_text(nc, encoding='utf-8')")
    w("    return mod, ch")
    nl()
    nl()
    w("def preview_diff(source_code, rules):")
    w("    '''Return unified diff string.'''")
    w("    nc, ch = migrate_code(source_code, rules)")
    w("    if nc == source_code: return 'No changes would be made.'")
    w("    d = difflib.unified_diff(source_code.splitlines(keepends=True),")
    w("        nc.splitlines(keepends=True), fromfile='original', tofile='migrated')")
    w("    hdr = 'Changes:\\n' + '\\n'.join('  - ' + c for c in ch) + '\\n\\n'")
    w("    return hdr + ''.join(d)")
    nl()
    nl()
    # CLI
    w("def main():")
    w("    p = argparse.ArgumentParser(description='" + package_name + " migrator')")
    w("    s = p.add_subparsers(dest='cmd')")
    nl()
    w("    lv = s.add_parser('list-versions')")
    nl()
    w("    m = s.add_parser('migrate')")
    w("    m.add_argument('path')")
    w("    m.add_argument('--from', dest='fv', required=True)")
    w("    m.add_argument('--to', dest='tv', default='latest')")
    w("    m.add_argument('--dry-run', action='store_true')")
    w("    m.add_argument('--no-backup', action='store_true')")
    w("    m.add_argument('--preview', action='store_true')")
    nl()
    w("    val = s.add_parser('validate')")
    w("    val.add_argument('file')")
    nl()
    w("    args = p.parse_args()")
    nl()
    w("    if args.cmd == 'list-versions':")
    w("        print('\\nAvailable versions for " + library_name + ":')")
    w("        for v in _versions():")
    w("            n = len(MIGRATION_DATA[v])")
    w("            print('  v' + v + '  (' + str(n) + ' rule' + ('s' if n!=1 else '') + ')')")
    w("        print()")
    w("        return")
    nl()
    w("    if args.cmd == 'validate':")
    w("        code = Path(args.file).read_text(encoding='utf-8')")
    w("        try: cst.parse_module(code); print('OK:', args.file)")
    w("        except Exception as e: print('FAIL:', e); sys.exit(1)")
    w("        return")
    nl()
    w("    if args.cmd == 'migrate':")
    w("        rules, tgt, up = _resolve(args.fv, args.tv)")
    w("        d = 'Upgrading' if up else 'Downgrading'")
    w("        print('\\n' + d + ': v' + args.fv + ' to v' + tgt)")
    w("        print('Applying ' + str(len(rules)) + ' rule(s)...')")
    w("        sp = Path(args.path)")
    w("        files = list(sp.rglob('*.py')) if sp.is_dir() else [sp]")
    w("        mc = 0")
    w("        for f in files:")
    w("            if args.preview:")
    w("                src = f.read_text(encoding='utf-8')")
    w("                diff = preview_diff(src, rules)")
    w("                if diff != 'No changes would be made.':")
    w("                    print('\\n=== ' + str(f) + ' ===')")
    w("                    print(diff)")
    w("            else:")
    w("                mod, ch = migrate_file(f, rules, dry_run=args.dry_run, backup=not args.no_backup)")
    w("                if mod or ch:")
    w("                    print('\\n  ' + str(f) + ':')")
    w("                    for c in ch: print('    + ' + c)")
    w("                    mc += 1")
    w("        tag = '[DRY RUN] ' if args.dry_run else ''")
    w("        verb = 'would be modified' if args.dry_run else 'modified'")
    w("        print('\\n' + tag + 'Done: ' + str(mc) + '/' + str(len(files)) + ' file(s) ' + verb + '.')")
    w("        return")
    nl()
    w("    p.print_help()")
    nl()
    nl()
    w("if __name__ == '__main__':")
    w("    main()")
    nl()

    return "\n".join(L)


class MigratorGenerator:
    """
    Generates a complete, distributable Python migrator package from
    a list of VersionChangelog objects.
    """

    def __init__(self, library_name: str, package_name: str = None):
        self.library_name = library_name
        self.package_name = package_name or (
            library_name.lower().replace("-", "_").replace(" ", "_") + "_migrator"
        )

    def generate(self, changelogs: List[VersionChangelog], output_dir: Path) -> Path:
        """Generate a complete migrator package. Returns path to output directory."""
        output_dir = Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)
        pkg_dir = output_dir / self.package_name
        pkg_dir.mkdir(exist_ok=True)

        # Build migration data: {version: [rule_dicts]}
        migration_data = {}
        for vc in changelogs:
            if vc.rules:
                migration_data[vc.version] = [r.to_dict() for r in vc.rules]

        versions = sorted(migration_data.keys())
        version_range = f"{versions[0]} - {versions[-1]}" if versions else "N/A"
        generated_date = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        # Write __main__.py
        main_src = _build_main_module(
            package_name=self.package_name,
            library_name=self.library_name,
            migration_data=migration_data,
            version_range=version_range,
            generated_date=generated_date,
        )
        (pkg_dir / "__main__.py").write_text(main_src, encoding="utf-8")

        # Write __init__.py
        (pkg_dir / "__init__.py").write_text(
            f'"""Auto-generated migrator for {self.library_name}"""\n',
            encoding="utf-8",
        )

        # Write setup.py
        (output_dir / "setup.py").write_text(
            SETUP_PY_TEMPLATE.format(
                package_name=self.package_name,
                package_version="1.0.0",
                library_name=self.library_name,
            ),
            encoding="utf-8",
        )

        # Write README.md
        version_list = "\n".join(
            f"- **v{v}** — {len(migration_data[v])} rule(s)" for v in versions
        )
        (output_dir / "README.md").write_text(
            README_TEMPLATE.format(
                package_name=self.package_name,
                library_name=self.library_name,
                version_list=version_list,
                generated_date=generated_date,
            ),
            encoding="utf-8",
        )

        # Write migration_rules.json
        raw_export = {
            "library": self.library_name,
            "generated": generated_date,
            "versions": [
                {
                    "version": vc.version,
                    "release_date": vc.release_date,
                    "rules": [r.to_dict() for r in vc.rules],
                }
                for vc in changelogs
            ],
        }
        (output_dir / "migration_rules.json").write_text(
            json.dumps(raw_export, indent=2), encoding="utf-8"
        )

        print(f"\n✅ Migrator package generated!")
        print(f"   Output    : {output_dir}")
        print(f"   Package   : {self.package_name}")
        print(f"   Versions  : {version_range}")
        print(f"   Rule sets : {len(migration_data)}")
        print(f"\n   Install   : pip install -e {output_dir}")
        print(f"   Run       : python -m {self.package_name} list-versions")

        return output_dir