"""Shared library for MigratorGen platform."""

from .auth import (
    Role,
    create_access_token,
    create_refresh_token,
    decode_token,
    generate_api_key,
    has_permission,
    hash_password,
    verify_api_key,
    verify_password,
)
from .cache import CacheManager
from .database import (
    APIKey,
    AuditLog,
    BillingSubscription,
    MigrationJob,
    MigrationSession,
    Tenant,
    User,
    get_session,
    init_db,
)
from .exceptions import (
    AuthenticationError,
    ConflictError,
    DependencyError,
    FileTooLargeError,
    MigrationError,
    MigratorBaseException,
    NotFoundError,
    ParsingError,
    RateLimitError,
    RuleValidationError,
    TimeoutError,
    UnsupportedFileTypeError,
    ValidationError,
    global_exception_handler,
    init_sentry,
)
from .logging import MigratorLogger, get_logger, setup_logging
from .metrics import MetricsCollector, setup_metrics, track_migration_end, track_migration_start
from .utils import (
    format_bytes,
    format_duration,
    generate_request_id,
    retry_with_backoff,
    safe_filename,
    utc_now,
)

__version__ = "0.1.0"
__all__ = [
    "setup_logging",
    "get_logger",
    "MigratorLogger",
    "MigratorBaseException",
    "ValidationError",
    "RuleValidationError",
    "ParsingError",
    "MigrationError",
    "FileTooLargeError",
    "UnsupportedFileTypeError",
    "RateLimitError",
    "AuthenticationError",
    "DependencyError",
    "TimeoutError",
    "ConflictError",
    "NotFoundError",
    "global_exception_handler",
    "init_sentry",
    "setup_metrics",
    "track_migration_start",
    "track_migration_end",
    "MetricsCollector",
    "CacheManager",
    "get_session",
    "init_db",
    "MigrationJob",
    "MigrationSession",
    "Tenant",
    "User",
    "APIKey",
    "AuditLog",
    "BillingSubscription",
    "generate_request_id",
    "utc_now",
    "safe_filename",
    "format_bytes",
    "format_duration",
    "retry_with_backoff",
    "Role",
    "hash_password",
    "verify_password",
    "create_access_token",
    "create_refresh_token",
    "decode_token",
    "generate_api_key",
    "verify_api_key",
    "has_permission",
]
