import { NextResponse } from "next/server";
import { readFile, readdir } from "node:fs/promises";
import path from "node:path";
import JSZip from "jszip";
import { getUserPackById } from "@/lib/packs";
import { requireSession, errorResponse } from "@/lib/api-helpers";

interface RouteContext {
  params: { id: string };
}

const ENGINE_DIR = path.resolve(process.cwd(), "..", "sdk", "python", "src", "migrator_gen", "core");
const SDK_VERSION = "0.2.0";

async function readEngineFiles(): Promise<Record<string, string>> {
  const files: Record<string, string> = {};
  const entries = await readdir(ENGINE_DIR);
  for (const entry of entries) {
    if (!entry.endsWith(".py")) continue;
    const content = await readFile(path.join(ENGINE_DIR, entry), "utf-8");
    files[entry] = content;
  }
  return files;
}

function generatePyprojectToml(library: string, name: string, description: string, versionCount: number, ruleCount: number): string {
  const safeName = library.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
  return `[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "${safeName}-migration"
version = "${SDK_VERSION}"
description = "${description || `Migration rules for ${library}`}"
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
dependencies = [
    "migrator-gen>=${SDK_VERSION}",
    "libcst>=1.0.0",
    "pydantic>=2.0.0",
]

[project.scripts]
${safeName}-migrate = "${safeName}_migration.cli:main"

[tool.hatch.build.targets.wheel]
packages = ["${safeName}_migration"]
`;
}

function generateReadme(library: string, name: string, description: string, versionCount: number, ruleCount: number): string {
  return `# ${name || library} Migration Pack

${description || `Automated migration rules for ${library}.`}

## Overview

- **Library:** ${library}
- **Versions:** ${versionCount}
- **Rules:** ${ruleCount}
- **Generated by:** MigratorGen

## Installation

\`\`\`bash
pip install -e .
\`\`\`

## Usage

### As a CLI tool

\`\`\`bash
${library.toLowerCase().replace(/[^a-z0-9]+/g, "-")}-migrate --source my_code.py --target-version 2.0.0
\`\`\`

### As a Python library

\`\`\`python
from migrator_gen import SyncMigrationClient

client = SyncMigrationClient(base_url="http://localhost:8000")
result = client.migrate(
    source_code=open("my_code.py").read(),
    rules=open("migration-pack.json").read(),
    target_version="2.0.0",
)
print(result.transformed_code)
\`\`\`

### Using the migration pack

The \`migration-pack.json\` file contains all the rules for this library.
You can load it directly:

\`\`\`python
import json

with open("migration-pack.json") as f:
    pack = json.load(f)

for version in pack["versions"]:
    print(f"Version {version['version']}: {len(version['rules'])} rules")
\`\`\`

## Updating Rules

If you need to add or modify rules, you can:

1. Edit \`migration-pack.json\` directly
2. Use the MigratorGen web interface at https://migratorgen.vercel.app
3. Use the CLI: \`migrator-gen rules add --file migration-pack.json\`

## License

MIT
`;
}

function generateCli(safeName: string, library: string): string {
  return `"""CLI entry point for ${library} migration pack."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


def main() -> None:
    parser = argparse.ArgumentParser(
        description="${library} migration tool powered by MigratorGen"
    )
    parser.add_argument(
        "--source", "-s",
        required=True,
        help="Path to the Python source file to migrate",
    )
    parser.add_argument(
        "--target-version", "-t",
        default="latest",
        help="Target version to migrate to (default: latest)",
    )
    parser.add_argument(
        "--pack",
        default="migration-pack.json",
        help="Path to the migration pack JSON file",
    )
    parser.add_argument(
        "--output", "-o",
        help="Output file path (default: stdout)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show diff without applying changes",
    )

    args = parser.parse_args()

    source_path = Path(args.source)
    if not source_path.exists():
        print(f"Error: Source file not found: {args.source}", file=sys.stderr)
        sys.exit(1)

    pack_path = Path(args.pack)
    if not pack_path.exists():
        print(f"Error: Migration pack not found: {args.pack}", file=sys.stderr)
        sys.exit(1)

    source_code = source_path.read_text(encoding="utf-8")
    pack_data = json.loads(pack_path.read_text(encoding="utf-8"))

    # Flatten all rules from all versions
    rules = []
    for version in pack_data.get("versions", []):
        rules.extend(version.get("rules", []))

    if not rules:
        print("No rules found in migration pack.", file=sys.stderr)
        sys.exit(1)

    print(f"Loaded {len(rules)} rules from {args.pack}", file=sys.stderr)

    try:
        from migrator_gen import SyncMigrationClient

        client = SyncMigrationClient()
        result = client.migrate(
            source_code=source_code,
            rules=json.dumps(rules),
            target_version=args.target_version,
        )

        if args.dry_run:
            print("=== Original ===")
            print(result.original_code)
            print("\\n=== Transformed ===")
            print(result.transformed_code)
            print(f"\\nChanges: {result.change_count}")
            print(f"Confidence: {result.average_confidence:.0%}")
        else:
            output = args.output
            if output:
                Path(output).write_text(result.transformed_code, encoding="utf-8")
                print(f"Written to {output}", file=sys.stderr)
            else:
                print(result.transformed_code)

    except ImportError:
        print(
            "Error: migrator-gen SDK not installed. Run: pip install migrator-gen",
            file=sys.stderr,
        )
        sys.exit(1)
    except Exception as e:
        print(f"Migration failed: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
`;
}

export async function GET(request: Request, context: RouteContext) {
  try {
    const auth = await requireSession();
    if (!auth.ok) return auth.response;

    const packId = context.params.id;
    const packData = await getUserPackById(packId);
    if (!packData) return NextResponse.json({ error: "Pack not found" }, { status: 404 });

    const url = new URL(request.url);
    const incremental = url.searchParams.get("incremental") === "true";

    const library = (packData.library as string) ?? packId;
    const name = (packData.name as string) ?? library;
    const description = (packData.description as string) ?? "";
    const versions = (packData.versions as Array<{ version: string; rules: unknown[] }>) ?? [];
    const ruleCount = versions.reduce((sum, v) => sum + (v.rules?.length ?? 0), 0);
    const safeName = library.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");

    const zip = new JSZip();

    if (incremental) {
      const packJson = {
        library,
        name,
        description,
        schema_version: "1.0",
        versions,
      };

      zip.file("migration-pack.json", JSON.stringify(packJson, null, 2));

      zip.file(
        "CHANGELOG.md",
        `# Migration Pack Update\n\n` +
          `**Library:** ${library}\n` +
          `**Versions:** ${versions.length}\n` +
          `**Rules:** ${ruleCount}\n\n` +
          `## How to Update\n\n` +
          `1. Copy \`migration-pack.json\` to replace the existing one in your project root\n` +
          `2. Reinstall if needed: \`pip install -e .\`\n` +
          `3. Verify: \`${safeName}-migrate --help\`\n\n` +
          `## Files to Replace\n\n` +
          `\`\`\`\n` +
          `migration-pack.json  <- replace this file\n` +
          `\`\`\`\n`,
      );

      zip.file(
        "README.md",
        `# Incremental Update\n\n` +
          `This archive contains only the updated migration rules.\n` +
          `Replace \`migration-pack.json\` in your existing project.\n\n` +
          `For a complete package with all engine files, use the full export.`,
      );
    } else {
      const engineFiles = await readEngineFiles();

      for (const [filename, content] of Object.entries(engineFiles)) {
        zip.file(`${safeName}_migration/engine/${filename}`, content);
      }

      const packJson = {
        library,
        name,
        description,
        schema_version: "1.0",
        versions,
      };
      zip.file(`${safeName}_migration/engine/__init__.py`, "");
      zip.file(`${safeName}_migration/__init__.py`, `"""${name} migration pack for ${library}."""\n`);
      zip.file(`${safeName}_migration/migration-pack.json`, JSON.stringify(packJson, null, 2));
      zip.file(
        `${safeName}_migration/cli.py`,
        generateCli(safeName, library),
      );
      zip.file(
        "pyproject.toml",
        generatePyprojectToml(library, name, description, versions.length, ruleCount),
      );
      zip.file(
        "README.md",
        generateReadme(library, name, description, versions.length, ruleCount),
      );
    }

    const buffer = await zip.generateAsync({ type: "nodebuffer", compression: "DEFLATE" });
    const filename = incremental
      ? `${safeName}-migration-update.zip`
      : `${safeName}-migration-pack.zip`;

    return new NextResponse(new Uint8Array(buffer), {
      headers: {
        "Content-Type": "application/zip",
        "Content-Disposition": `attachment; filename="${filename}"`,
      },
    });
  } catch (err) {
    return errorResponse(err);
  }
}

export const runtime = "nodejs";
